name: Build and Upload APKs

on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.3

      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK dependencies
        uses: android-actions/setup-android@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Make build scripts executable
        run: chmod +x art/buildScripts/android/*.sh

      - name: Build 32-bit APK
        run: bash art/buildScripts/android/build_x32.sh

      - name: Build 64-bit APK
        run: bash art/buildScripts/android/build_x64.sh

      - name: Debug List APK locations
        run: find . -type f -name "*.apk"

      - name: Prepare docs/builds folder
        run: mkdir -p docs/builds

      - name: Copy APKs to docs/builds
        run: cp export/android/bin/app/build/outputs/apk/debug/*.apk docs/builds/ || echo "No APKs found"

      - name: Commit APKs to repository
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/builds/*.apk || echo "No APKs to add"
          git commit -m "Add latest APK builds [auto]" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"
